CREATE DATABASE WagiWeb;

CREATE TABLE WebUsers (
    WUId INT NOT NULL PRIMARY KEY IDENTITY(1, 1),
    WULogin VARCHAR(255) NOT NULL,
    WUPassword VARCHAR(255) NOT NULL,
    WUIsActive INT NOT NULL DEFAULT 1,
    WURole INT NOT NULL DEFAULT 4,
    WUCreated DATETIME NOT NULL DEFAULT GETDATE(),
    WUEdited DATETIME NOT NULL DEFAULT GETDATE()
);

CREATE TABLE Roles (
    RId INT NOT NULL PRIMARY KEY IDENTITY(1, 1),
    RName VARCHAR(255) NOT NULL,
    RRaportyAccess INT NOT NULL DEFAULT 0,
    RSerwisAccess INT NOT NULL DEFAULT 0,
    RUstawieniaAccess INT NOT NULL DEFAULT 0,
    RUzytkownicyAccess INT NOT NULL DEFAULT 0,
);

CREATE TABLE PorownanieStatus (
    PSId INT NOT NULL PRIMARY KEY IDENTITY(1,1),
    PSNazwa VARCHAR(255)
);

CREATE TABLE ReportDescriptions (
    Id INT NOT NULL PRIMARY KEY IDENTITY(1,1),
    ReportId INT NOT NULL,
    Description VARCHAR(255) NOT NULL,
    CreatedAt DATETIME NOT NULL DEFAULT GETDATE(),
    Author VARCHAR(255) NOT NULL
);